import { createContext, useContext } from 'react'

export const LangCtx = createContext({ lang: 'pl', t: {}, setLang: () => { } })
export const useT = () => useContext(LangCtx)

export const I18N = {
    pl: {
        subtitle: 'Panel wewnętrzny', period: 'Okres',
        role_admin: 'Admin', role_accountant: 'Księgowość', role_viewer: 'Podgląd',
        nav_workspace: 'Przestrzeń robocza', nav_accounting: 'Księgowość', nav_catalog: 'Katalog', nav_system: 'System',
        nav_files: 'Pliki', nav_invoices_sales: 'Faktury sprzedaży', nav_invoices_cost: 'Faktury kosztowe',
        nav_orders: 'Zamówienia', nav_products: 'Produkty', nav_close: 'Zamknięcie miesiąca',
        nav_users: 'Zespół', nav_settings: 'Ustawienia',
        files_title: 'Pliki',
        files_sub: 'Wszystkie dokumenty w kontenerze Azure Blob — faktury, raporty, wyciągi, archiwa miesięczne.',
        btn_upload: 'Wgraj plik', btn_close_month: 'Zamknij miesiąc',
        search_placeholder: 'Szukaj w bieżącym folderze…',
        filter_all: 'Wszystkie', filter_pdf: 'PDF', filter_xml: 'XML / KSeF', filter_csv: 'CSV', filter_archive: 'Archiwa',
        col_name: 'Nazwa', col_size: 'Rozmiar', col_modified: 'Zmodyfikowano', col_meta: 'Opis',
        dropzone_hint: 'Przeciągnij plik tutaj lub użyj „Wgraj plik" — wymaga roli accountant+.',
        dropzone_active: 'Puść, żeby wgrać do bieżącego folderu',
        sales_title: 'Faktury sprzedaży', sales_sub: 'Synchronizacja z Fakturownia API · kwiecień 2026.',
        col_inv_no: 'Numer', col_inv_date: 'Data', col_inv_buyer: 'Nabywca', col_inv_net: 'Netto', col_inv_vat: 'VAT', col_inv_gross: 'Brutto', col_inv_status: 'Status',
        st_paid: 'opłacona', st_unpaid: 'nieopłacona', st_overdue: 'przeterm.', st_issued: 'wystawiona', st_draft: 'szkic',
        products_title: 'Produkty', products_sub: 'Katalog Fakturownia — aktywne SKU, pojemności, opakowania.',
        col_sku: 'SKU', col_name2: 'Nazwa', col_capacity: 'Pojemność', col_pkg: 'Opakowanie', col_price: 'Cena netto', col_active: 'Status',
        orders_title: 'Zamówienia', orders_sub: 'Zamówienia hurtowe · dokumenty WZ · status realizacji.',
        col_order_no: 'Nr zamówienia', col_order_date: 'Data', col_order_customer: 'Klient', col_order_items: 'Pozycji', col_order_wz: 'WZ', col_order_status: 'Status',
        st_new: 'nowe', st_prep: 'pakowanie', st_sent: 'wysłane', st_delivered: 'dostarczone',
        close_title: 'Zamknięcie miesiąca',
        close_sub: 'Pipeline 8-stopniowy: preflight → faktury → JPK → KSeF → archiwum → e-mail do księgowej.',
        close_status_ready: 'Gotowe do uruchomienia', close_status_running: 'Trwa zamykanie…',
        close_status_done: 'Zakończono pomyślnie', close_status_error: 'Błąd pipeline',
        close_step: 'Krok', close_dryrun: 'Symulacja (dry-run)', close_run: 'Uruchom pipeline',
        settings_title: 'Ustawienia', settings_sub: 'Konfiguracja integracji, sekretów i tożsamości Entra ID.',
        s_org: 'Organizacja', s_org_sub: 'Dane firmy wysyłane na e-mail do księgowej.',
        s_integr: 'Integracje', s_integr_sub: 'Fakturownia, KSeF, Zoho Mail, Canva.',
        s_secrets: 'Sekrety', s_secrets_sub: 'macOS Keychain · konto humio.',
        users_title: 'Zespół', users_sub: 'Role przypisane w Azure Entra ID — Enterprise applications → zdrovena-api.',
        pill_ok: 'aktywna', footer_health: 'healthy', footer_env: 'prod', footer_version: 'API v2.0.0',
        login_title: 'Zaloguj się', login_sub: 'Wymagane konto Microsoft z rolą zdrovena-*.',
        login_btn: 'Zaloguj przez Microsoft', login_hint: 'Azure Entra ID · SSO', logout: 'Wyloguj',
    },
    en: {
        subtitle: 'Internal panel', period: 'Period',
        role_admin: 'Admin', role_accountant: 'Accountant', role_viewer: 'Viewer',
        nav_workspace: 'Workspace', nav_accounting: 'Accounting', nav_catalog: 'Catalog', nav_system: 'System',
        nav_files: 'Files', nav_invoices_sales: 'Sales invoices', nav_invoices_cost: 'Cost invoices',
        nav_orders: 'Orders', nav_products: 'Products', nav_close: 'Month close',
        nav_users: 'Team', nav_settings: 'Settings',
        files_title: 'Files',
        files_sub: 'All documents in the Azure Blob container — invoices, reports, bank statements, monthly archives.',
        btn_upload: 'Upload', btn_close_month: 'Close month',
        search_placeholder: 'Search current folder…',
        filter_all: 'All', filter_pdf: 'PDF', filter_xml: 'XML / KSeF', filter_csv: 'CSV', filter_archive: 'Archives',
        col_name: 'Name', col_size: 'Size', col_modified: 'Modified', col_meta: 'Description',
        dropzone_hint: 'Drop a file here or use Upload — requires accountant+ role.',
        dropzone_active: 'Release to upload into current folder',
        sales_title: 'Sales invoices', sales_sub: 'Synced from Fakturownia API · April 2026.',
        col_inv_no: 'Number', col_inv_date: 'Date', col_inv_buyer: 'Buyer', col_inv_net: 'Net', col_inv_vat: 'VAT', col_inv_gross: 'Gross', col_inv_status: 'Status',
        st_paid: 'paid', st_unpaid: 'unpaid', st_overdue: 'overdue', st_issued: 'issued', st_draft: 'draft',
        products_title: 'Products', products_sub: 'Fakturownia catalog — active SKUs, capacities, packaging.',
        col_sku: 'SKU', col_name2: 'Name', col_capacity: 'Capacity', col_pkg: 'Packaging', col_price: 'Net price', col_active: 'Status',
        orders_title: 'Orders', orders_sub: 'Wholesale orders · WZ documents · fulfillment status.',
        col_order_no: 'Order #', col_order_date: 'Date', col_order_customer: 'Customer', col_order_items: 'Items', col_order_wz: 'WZ', col_order_status: 'Status',
        st_new: 'new', st_prep: 'packing', st_sent: 'shipped', st_delivered: 'delivered',
        close_title: 'Month close',
        close_sub: '8-step pipeline: preflight → invoices → JPK → KSeF → archive → e-mail to accountant.',
        close_status_ready: 'Ready to run', close_status_running: 'Closing in progress…',
        close_status_done: 'Completed successfully', close_status_error: 'Pipeline error',
        close_step: 'Step', close_dryrun: 'Dry run', close_run: 'Run pipeline',
        settings_title: 'Settings', settings_sub: 'Integrations, secrets, and Entra ID identity.',
        s_org: 'Organization', s_org_sub: 'Company data sent in accountant e-mails.',
        s_integr: 'Integrations', s_integr_sub: 'Fakturownia, KSeF, Zoho Mail, Canva.',
        s_secrets: 'Secrets', s_secrets_sub: 'macOS Keychain · account humio.',
        users_title: 'Team', users_sub: 'Roles assigned in Azure Entra ID — Enterprise applications → zdrovena-api.',
        pill_ok: 'active', footer_health: 'healthy', footer_env: 'prod', footer_version: 'API v2.0.0',
        login_title: 'Sign in', login_sub: 'A Microsoft account with a zdrovena-* role is required.',
        login_btn: 'Sign in with Microsoft', login_hint: 'Azure Entra ID · SSO', logout: 'Sign out',
    },
}
