import { createContext, useContext } from 'react'

export const LangCtx = createContext({ lang: 'pl', t: {}, setLang: () => { } })
export const useT = () => useContext(LangCtx)

export const I18N = {
    pl: {
        subtitle: 'Panel wewnętrzny', period: 'Okres',
        role_admin: 'Admin', role_accountant: 'Księgowość', role_viewer: 'Podgląd',
        nav_workspace: 'Przestrzeń robocza', nav_accounting: 'Księgowość', nav_catalog: 'Katalog', nav_system: 'System',
        nav_files: 'Pliki', nav_invoices_sales: 'Faktury sprzedaży', nav_invoices_cost: 'Faktury kosztowe',
        nav_orders: 'Zamówienia', nav_products: 'Produkty', nav_close: 'Zamknięcie miesiąca',
        nav_users: 'Zespół', nav_settings: 'Ustawienia', nav_shipping: 'Wysyłki', nav_dlq: 'Kolejka błędów', nav_damage: 'Uszkodzenia',
        shipping_title: 'Wysyłki', shipping_sub: 'Drafty przesyłek tworzone automatycznie przy złożeniu zamówienia Shopify.',
        shipping_drafts_count: 'draftów', shipping_errors: 'błędów',
        sh_search: 'Szukaj po numerze lub kliencie…',
        sh_filter_all_status: 'Wszystkie statusy', sh_status_pending: 'oczekujące', sh_status_created: 'nadane', sh_status_needs_review: 'do sprawdzenia', sh_status_error: 'błąd', sh_status_pending_confirmation: 'czeka na Allegro',
        sh_confirm_pending: 'Sprawdź status', sh_confirm_pending_busy: 'Sprawdzanie…',
        sh_filter_all_courier: 'Wszyscy kurierzy',
        sh_select_all: 'Zaznacz wszystkie', sh_selected_all: 'Zaznaczono wszystkie',
        sh_expand: 'Rozwiń', sh_collapse: 'Zwiń',
        sh_pickup_done: 'podjazd ✓', sh_apaczka_service_label: 'Serwis Apaczka', sh_apaczka_service_placeholder: '— wybierz serwis —', sh_apaczka_service_save: 'Zapisz', sh_apaczka_service_save_busy: 'Zapisywanie…',
        sh_pickup_date: 'Data podjazdu', sh_time_from: 'Od', sh_time_to: 'Do',
        sh_min_window: 'Minimalne okno: 2 godziny', sh_cancel: 'Anuluj', sh_confirm: 'Potwierdź',
        files_title: 'Pliki',
        files_sub: 'Wszystkie dokumenty w kontenerze Azure Blob — faktury, raporty, wyciągi, archiwa miesięczne.',
        kpi_revenue: 'Przychód (netto)', kpi_sales_count: 'Faktur sprzedaży',
        kpi_files: 'Pliki w kontenerze', kpi_files_sub: 'od ostatniego załadowania',
        kpi_today: 'wgrane dziś',
        kpi_pipeline: 'Status pipeline', kpi_pipeline_ready: 'Gotowe',
        kpi_no_api: 'brak integracji API',
        btn_upload: 'Wgraj plik', btn_close_month: 'Zamknij miesiąc',
        search_placeholder: 'Szukaj w bieżącym folderze…',
        filter_all: 'Wszystkie', filter_pdf: 'PDF', filter_xml: 'XML / KSeF', filter_csv: 'CSV', filter_archive: 'Archiwa',
        col_name: 'Nazwa', col_size: 'Rozmiar', col_modified: 'Zmodyfikowano', col_meta: 'Opis',
        dropzone_hint: 'Przeciągnij plik tutaj lub użyj „Wgraj plik" — wymaga roli accountant+.',
        dropzone_active: 'Puść, żeby wgrać do bieżącego folderu',
        sales_title: 'Faktury sprzedaży', sales_sub: 'Synchronizacja z Fakturownia API · kwiecień 2026.',
        sales_sub_live: 'Fakturownia API — live',
        col_inv_no: 'Numer', col_inv_date: 'Data', col_inv_buyer: 'Nabywca', col_inv_net: 'Netto', col_inv_vat: 'VAT', col_inv_gross: 'Brutto', col_inv_status: 'Status',
        st_paid: 'opłacona', st_unpaid: 'nieopłacona', st_overdue: 'przeterm.', st_issued: 'wystawiona', st_draft: 'szkic',
        products_title: 'Produkty', products_sub: 'Katalog Fakturownia — aktywne SKU, pojemności, opakowania.',
        products_active_only: 'Tylko aktywne',
        col_sku: 'SKU', col_name2: 'Nazwa', col_capacity: 'Pojemność', col_pkg: 'Opakowanie', col_price: 'Cena netto', col_active: 'Status',
        orders_title: 'Zamówienia', orders_sub: 'Zamówienia hurtowe · dokumenty WZ · status realizacji.',
        col_order_no: 'Nr zamówienia', col_order_date: 'Data', col_order_customer: 'Klient', col_order_items: 'Pozycji', col_order_wz: 'WZ', col_order_status: 'Status',
        st_new: 'nowe', st_prep: 'pakowanie', st_sent: 'wysłane', st_delivered: 'dostarczone',
        close_title: 'Zamknięcie miesiąca',
        close_sub: 'Pipeline 8-stopniowy: preflight → faktury → JPK → KSeF → archiwum → e-mail do księgowej.',
        close_status_ready: 'Gotowe do uruchomienia', close_status_running: 'Trwa zamykanie…',
        close_status_done: 'Zakończono pomyślnie', close_status_error: 'Błąd pipeline',
        close_step: 'Krok', close_dryrun: 'Symulacja (dry-run)', close_run: 'Uruchom pipeline',
        close_month: 'Miesiąc', close_year: 'Rok',
        close_result: 'Wynik zamknięcia',
        close_sales_count: 'faktury sprzedaży', close_cost_count: 'faktury kosztowe',
        close_warnings: 'Ostrzeżenia', close_errors_label: 'Błędy',
        close_email_sent: 'e-mail wysłany', close_email_pending: 'e-mail nie wysłany',
        settings_title: 'Ustawienia', settings_sub: 'Konfiguracja integracji, sekretów i tożsamości Entra ID.',
        s_org: 'Organizacja', s_org_sub: 'Dane firmy wysyłane na e-mail do księgowej.',
        s_integr: 'Integracje', s_integr_sub: 'Fakturownia, KSeF, Zoho Mail, Canva.',
        s_secrets: 'Sekrety', s_secrets_sub: 'macOS Keychain · konto humio.',
        users_title: 'Zespół', users_sub: 'Role przypisane w Azure Entra ID — Enterprise applications → zdrovena-api.',
        pill_ok: 'aktywna', pill_inactive: 'nieaktywny', empty: 'Brak wyników.', footer_health: 'healthy', footer_env: 'prod', footer_version: 'API v2.0.0',
        login_title: 'Zaloguj się', login_sub: 'Wymagane konto Microsoft z rolą zdrovena-*.',
        login_btn: 'Zaloguj przez Microsoft', login_hint: 'Azure Entra ID · SSO', logout: 'Wyloguj',
    },
    en: {
        subtitle: 'Internal panel', period: 'Period',
        role_admin: 'Admin', role_accountant: 'Accountant', role_viewer: 'Viewer',
        nav_workspace: 'Workspace', nav_accounting: 'Accounting', nav_catalog: 'Catalog', nav_system: 'System',
        nav_files: 'Files', nav_invoices_sales: 'Sales invoices', nav_invoices_cost: 'Cost invoices',
        nav_orders: 'Orders', nav_products: 'Products', nav_close: 'Month close',
        nav_users: 'Team', nav_settings: 'Settings', nav_shipping: 'Shipping', nav_dlq: 'Error queue', nav_damage: 'Damages',
        shipping_title: 'Shipping', shipping_sub: 'Shipment drafts created automatically when a Shopify order is placed.',
        shipping_drafts_count: 'drafts', shipping_errors: 'errors',
        sh_search: 'Search by order # or customer…',
        sh_filter_all_status: 'All statuses', sh_status_pending: 'pending', sh_status_created: 'created', sh_status_needs_review: 'to review', sh_status_error: 'error', sh_status_pending_confirmation: 'waiting on Allegro',
        sh_confirm_pending: 'Check status', sh_confirm_pending_busy: 'Checking…',
        sh_filter_all_courier: 'All couriers',
        sh_select_all: 'Select all', sh_selected_all: 'All selected',
        sh_expand: 'Expand all', sh_collapse: 'Collapse all',
        sh_pickup_done: 'pickup ✓', sh_apaczka_service_label: 'Apaczka service', sh_apaczka_service_placeholder: '— select service —', sh_apaczka_service_save: 'Save', sh_apaczka_service_save_busy: 'Saving…',
        sh_pickup_date: 'Pickup date', sh_time_from: 'From', sh_time_to: 'To',
        sh_min_window: 'Minimum window: 2 hours', sh_cancel: 'Cancel', sh_confirm: 'Confirm',
        files_title: 'Files',
        files_sub: 'All documents in the Azure Blob container — invoices, reports, bank statements, monthly archives.',
        kpi_revenue: 'Revenue (net)', kpi_sales_count: 'Sales invoices',
        kpi_files: 'Files in container', kpi_files_sub: 'since last load',
        kpi_today: 'uploaded today',
        kpi_pipeline: 'Pipeline status', kpi_pipeline_ready: 'Ready',
        kpi_no_api: 'no API integration',
        btn_upload: 'Upload', btn_close_month: 'Close month',
        search_placeholder: 'Search current folder…',
        filter_all: 'All', filter_pdf: 'PDF', filter_xml: 'XML / KSeF', filter_csv: 'CSV', filter_archive: 'Archives',
        col_name: 'Name', col_size: 'Size', col_modified: 'Modified', col_meta: 'Description',
        dropzone_hint: 'Drop a file here or use Upload — requires accountant+ role.',
        dropzone_active: 'Release to upload into current folder',
        sales_title: 'Sales invoices', sales_sub: 'Synced from Fakturownia API · April 2026.',
        sales_sub_live: 'Fakturownia API — live',
        col_inv_no: 'Number', col_inv_date: 'Date', col_inv_buyer: 'Buyer', col_inv_net: 'Net', col_inv_vat: 'VAT', col_inv_gross: 'Gross', col_inv_status: 'Status',
        st_paid: 'paid', st_unpaid: 'unpaid', st_overdue: 'overdue', st_issued: 'issued', st_draft: 'draft',
        products_title: 'Products', products_sub: 'Fakturownia catalog — active SKUs, capacities, packaging.',
        products_active_only: 'Active only',
        col_sku: 'SKU', col_name2: 'Name', col_capacity: 'Capacity', col_pkg: 'Packaging', col_price: 'Net price', col_active: 'Status',
        orders_title: 'Orders', orders_sub: 'Wholesale orders · WZ documents · fulfillment status.',
        col_order_no: 'Order #', col_order_date: 'Date', col_order_customer: 'Customer', col_order_items: 'Items', col_order_wz: 'WZ', col_order_status: 'Status',
        st_new: 'new', st_prep: 'packing', st_sent: 'shipped', st_delivered: 'delivered',
        close_title: 'Month close',
        close_sub: '8-step pipeline: preflight → invoices → JPK → KSeF → archive → e-mail to accountant.',
        close_status_ready: 'Ready to run', close_status_running: 'Closing in progress…',
        close_status_done: 'Completed successfully', close_status_error: 'Pipeline error',
        close_step: 'Step', close_dryrun: 'Dry run', close_run: 'Run pipeline',
        close_month: 'Month', close_year: 'Year',
        close_result: 'Close result',
        close_sales_count: 'sales invoices', close_cost_count: 'cost invoices',
        close_warnings: 'Warnings', close_errors_label: 'Errors',
        close_email_sent: 'e-mail sent', close_email_pending: 'e-mail not sent',
        settings_title: 'Settings', settings_sub: 'Integrations, secrets, and Entra ID identity.',
        s_org: 'Organization', s_org_sub: 'Company data sent in accountant e-mails.',
        s_integr: 'Integrations', s_integr_sub: 'Fakturownia, KSeF, Zoho Mail, Canva.',
        s_secrets: 'Secrets', s_secrets_sub: 'macOS Keychain · account humio.',
        users_title: 'Team', users_sub: 'Roles assigned in Azure Entra ID — Enterprise applications → zdrovena-api.',
        pill_ok: 'active', pill_inactive: 'inactive', empty: 'No results.', footer_health: 'healthy', footer_env: 'prod', footer_version: 'API v2.0.0',
        login_title: 'Sign in', login_sub: 'A Microsoft account with a zdrovena-* role is required.',
        login_btn: 'Sign in with Microsoft', login_hint: 'Azure Entra ID · SSO', logout: 'Sign out',
    },
}
