#!/usr/bin/env bash
# scripts/bootstrap_azure.sh
#
# One-time setup: creates the Azure storage account used as Terraform remote state.
# Run ONCE before the first `terraform init`. Idempotent — safe to re-run.
#
# Usage:
#   chmod +x scripts/bootstrap_azure.sh
#   ./scripts/bootstrap_azure.sh
#
# After this script finishes it writes infra/terraform/backend.hcl with the
# correct values — do NOT commit that file.

set -euo pipefail

SUBSCRIPTION_ID="f8942601-3bfe-437d-b849-86f3b5519fea"
LOCATION="polandcentral"
STATE_RG="zdrovena-state-rg"
STATE_SA="zdrovenastate"          # must be globally unique + max 24 alphanum chars
STATE_CONTAINER="tfstate"
STATE_KEY="zdrovena.tfstate"

echo "▶ Setting subscription…"
az account set --subscription "$SUBSCRIPTION_ID"

echo "▶ Creating resource group '$STATE_RG'…"
az group create \
  --name "$STATE_RG" \
  --location "$LOCATION" \
  --output none

echo "▶ Creating storage account '$STATE_SA'…"
az storage account create \
  --name "$STATE_SA" \
  --resource-group "$STATE_RG" \
  --location "$LOCATION" \
  --sku Standard_LRS \
  --min-tls-version TLS1_2 \
  --allow-blob-public-access false \
  --output none

echo "▶ Enabling versioning (protects state files)…"
az storage account blob-service-properties update \
  --account-name "$STATE_SA" \
  --resource-group "$STATE_RG" \
  --enable-versioning true \
  --output none

echo "▶ Creating blob container '$STATE_CONTAINER'…"
az storage container create \
  --name "$STATE_CONTAINER" \
  --account-name "$STATE_SA" \
  --auth-mode login \
  --output none

# Write backend.hcl so `terraform init -backend-config=backend.hcl` works
BACKEND_FILE="$(dirname "$0")/../infra/terraform/backend.hcl"
mkdir -p "$(dirname "$BACKEND_FILE")"

cat > "$BACKEND_FILE" <<EOF
# Auto-generated by scripts/bootstrap_azure.sh — do NOT commit
resource_group_name  = "$STATE_RG"
storage_account_name = "$STATE_SA"
container_name       = "$STATE_CONTAINER"
key                  = "$STATE_KEY"
EOF

echo ""
echo "✅ Bootstrap complete."
echo ""
echo "Next steps:"
echo "  1. Fill in infra/terraform/terraform.tfvars (github_owner, azure_tenant_id)"
echo "  2. cd infra/terraform"
echo "  3. terraform init -backend-config=backend.hcl"
echo "  4. terraform plan -var-file=terraform.tfvars"
echo "  5. terraform apply -var-file=terraform.tfvars"
echo "  6. Copy Terraform outputs to GitHub Secrets (see outputs.tf)"
